server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://3.39.226.230:5432/image2d
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG9Dialect

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
